export default {
  ACTIONS: {},
  GETTERS: {},
  MUTATIONS: {},
  STATE: {
    APPSYNC: {
      JWT_TOKEN_PROMISE: "APPSYNC_JWT_TOKEN_PROMISE",
      JWT_TOKEN_PROMISE_REJECT: "APPSYNC_JWT_TOKEN_PROMISE_REJECT",
      JWT_TOKEN_PROMISE_RESOLVE: "APPSYNC_JWT_TOKEN_PROMISE_RESOLVE",
    },
  },
};
